### ISSUE TITLE
Fee estimation not working

### ISSUE THREAD

**Issue by jzbz** [decred/copay#17] opened 2016-03-07 20:32 UTC
Attempting to create a transaction using the "Send All" option results in the following error:

"Could not send payment: Insufficient funds for fee"

**Comment by v998** [comment] 2016-03-21 12:30
Strangely, there was already a fix for the web wallet in another issue a month ago. (Issue: https://github.com/decred/copay/issues/7) (PR: https://github.com/decred/copay/pull/13) (Commit: https://github.com/decred/copay/pull/13/commits/a583538d29679df07942dccab7a75dce654537d1)

However I still get this error currently, can you look into it? @alexlyp 

![image](https://cloud.githubusercontent.com/assets/7825360/13918596/6d0df786-efa3-11e5-955a-af81a3057925.png)

**Comment by jcvernaleo** [comment] 2016-04-11 17:30
@alexlyp does this look like a case of copay just using an old wallet when this happened?  If so I'd like to close the issue but not if it still happens.

**Comment by alexlyp** [comment] 2016-04-11 17:31
I'll verify that it works for me then I'll close or update this issue depending on results.

**Comment by alexlyp** [comment] 2016-04-11 17:49
I was just able to 2 send alls on mainnet. 

Going to close this issue for now.  If people are still running into it, I'll need more information about how it may have been tripped.

**Closed as completed by alexlyp** 2016-04-11 17:49 UTC
Labels: bug

**Comment by v998** [comment] 2016-04-12 10:31
Okay, I can confirm the "send all" works now.
